/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.seatunnel.engine.server.telemetry.log;

import java.util.regex.Pattern;

/**
 * Matches the exact file names that belong to one job log lifecycle.
 *
 * <p>The matcher intentionally rejects substring matches such as job 123 matching job 1234. It
 * accepts the active file, the unclassified sidecar used during mixed-version mode propagation, and
 * plain rolled files generated by the streaming log policy.
 */
public final class JobLogFileNameMatcher {

    /**
     * Suffix used when the engine cannot safely classify the job mode.
     *
     * <p>These files must still be downloadable and removable with the owning job.
     */
    private static final String UNCLASSIFIED_SUFFIX = ".unclassified";

    /**
     * Date-index suffix generated by the streaming RollingFile policy.
     *
     * <p>The matcher accepts only complete date-index suffixes to avoid prefix leakage.
     */
    private static final Pattern ROLLED_SUFFIX_PATTERN =
            Pattern.compile("\\.\\d{4}-\\d{2}-\\d{2}-\\d+");

    /**
     * Utility class.
     *
     * <p>All behavior is exposed through stateless matching helpers.
     */
    private JobLogFileNameMatcher() {}

    /**
     * Return whether the file name belongs exactly to the requested job id.
     *
     * @param fileName candidate file name without parent directories
     * @param jobId job id whose active, sidecar, or rolled files are expected
     * @return true only for active, unclassified, or date-index rolled job log names
     */
    public static boolean isJobLogFile(String fileName, long jobId) {
        String activeFileName = activeFileName(jobId);
        if (activeFileName.equals(fileName)
                || (activeFileName + UNCLASSIFIED_SUFFIX).equals(fileName)) {
            return true;
        }
        if (!fileName.startsWith(activeFileName + ".")) {
            return false;
        }
        return ROLLED_SUFFIX_PATTERN.matcher(fileName.substring(activeFileName.length())).matches();
    }

    /**
     * Return whether the file name is a rolled segment produced by the streaming RollingFile
     * policy. Rolled segments use a {@code .<yyyy-MM-dd>-<index>} suffix on top of the active file
     * name (e.g. {@code job-123.log.2026-08-05-1}) and are managed separately from the active file
     * so that long-running jobs can be pruned while still running.
     *
     * <p>This matcher is deliberately stricter than {@link #isJobLogFile(String, long)} for
     * pruning: it does NOT accept the {@code .unclassified} sidecar or the active file because
     * those are owned by the active lifecycle and must only be removed at job terminal state.
     *
     * <p>The match is anchored to the trailing suffix of the file name, so paths such as {@code
     * job-123.log.unclassified} or {@code job-123.log} are rejected.
     *
     * @param fileName candidate file name without parent directories
     * @return true only for file names ending with {@code .<yyyy-MM-dd>-<index>}
     */
    public static boolean isRolledSegment(String fileName) {
        if (fileName == null) {
            return false;
        }
        // Anchor on the trailing suffix so non-rolled files (active or .unclassified) are rejected.
        String tail = fileName;
        int slash = fileName.lastIndexOf('/');
        if (slash >= 0) {
            tail = fileName.substring(slash + 1);
        }
        int lastDot = tail.lastIndexOf('.');
        if (lastDot <= 0) {
            return false;
        }
        return ROLLED_SUFFIX_PATTERN.matcher(tail.substring(lastDot)).matches();
    }

    /**
     * Build the active log file name for one job id.
     *
     * @param jobId job id written in the Log4j job file name
     * @return active job log file name
     */
    public static String activeFileName(long jobId) {
        return "job-" + jobId + ".log";
    }
}
