/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.seatunnel.transform.python;

import org.apache.seatunnel.shade.com.fasterxml.jackson.core.type.TypeReference;
import org.apache.seatunnel.shade.org.apache.commons.lang3.StringUtils;

import org.apache.seatunnel.api.configuration.Option;
import org.apache.seatunnel.api.configuration.Options;
import org.apache.seatunnel.api.configuration.ReadonlyConfig;
import org.apache.seatunnel.api.table.catalog.Column;
import org.apache.seatunnel.api.table.catalog.PhysicalColumn;
import org.apache.seatunnel.api.table.catalog.SeaTunnelDataTypeConvertorUtil;
import org.apache.seatunnel.api.table.type.SeaTunnelDataType;
import org.apache.seatunnel.transform.common.ErrorHandleWay;
import org.apache.seatunnel.transform.common.TransformCommonOptions;
import org.apache.seatunnel.transform.exception.TransformException;

import lombok.Getter;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Set;

import static org.apache.seatunnel.transform.python.PythonTransformErrorCode.COLUMNS_MUST_NOT_EMPTY;
import static org.apache.seatunnel.transform.python.PythonTransformErrorCode.DEST_FIELD_MUST_NOT_EMPTY;
import static org.apache.seatunnel.transform.python.PythonTransformErrorCode.DUPLICATE_DEST_FIELD_ERROR;
import static org.apache.seatunnel.transform.python.PythonTransformErrorCode.PYTHON_SCRIPT_MUST_BE_CONFIGURED;
import static org.apache.seatunnel.transform.python.PythonTransformErrorCode.UNSUPPORTED_ERROR_HANDLE_WAY;

/** Immutable user-facing configuration for the Python transform. */
@Getter
public class PythonTransformConfig implements Serializable {

    /** Default python executable used when the user does not override the runtime. */
    private static final String DEFAULT_PYTHON_EXECUTABLE = "python3";

    /** Inline Python source code configured directly in the job definition. */
    public static final Option<String> SOURCE_CODE =
            Options.key("source_code")
                    .stringType()
                    .noDefaultValue()
                    .withDescription(
                            "Inline Python source code. The script must define process(row, context).");

    /** Path-based Python source configured on the runtime host. */
    public static final Option<String> SOURCE_CODE_PATH =
            Options.key("source_code_path")
                    .stringType()
                    .noDefaultValue()
                    .withDescription(
                            "Path to a Python script on the runtime server. The script must define process(row, context).");

    /** Python executable used to launch the worker subprocess. */
    public static final Option<String> PYTHON_EXECUTABLE =
            Options.key("python_executable")
                    .stringType()
                    .defaultValue(DEFAULT_PYTHON_EXECUTABLE)
                    .withDescription("Python executable used to launch the worker process.");

    /** Static configuration exposed to user scripts through the runtime context. */
    public static final Option<Map<String, Object>> SCRIPT_CONFIG =
            Options.key("script_config")
                    .type(new TypeReference<Map<String, Object>>() {})
                    .noDefaultValue()
                    .withDescription(
                            "Optional user-defined static configuration passed to the Python script.");

    /** Output field declarations appended to the transform result schema. */
    public static final Option<List<Map<String, String>>> COLUMNS =
            Options.key("columns")
                    .type(new TypeReference<List<Map<String, String>>>() {})
                    .noDefaultValue()
                    .withDescription("Output columns generated by the Python transform.");

    /** Output field name inside one columns entry. */
    public static final Option<String> DEST_FIELD =
            Options.key("dest_field")
                    .stringType()
                    .noDefaultValue()
                    .withDescription("Output field name returned by the Python transform.");

    /** Output field type inside one columns entry. */
    public static final Option<String> DEST_TYPE =
            Options.key("dest_type")
                    .stringType()
                    .defaultValue("string")
                    .withDescription("Output field type returned by the Python transform.");

    /** Row-level error handling strategy delegated to the common transform layer. */
    private final ErrorHandleWay errorHandleWay;

    /** Python executable used to launch the external worker process. */
    private final String pythonExecutable;

    /** Inline Python source code when the script is embedded in the job config. */
    private final String sourceCode;

    /** Runtime path to the Python source file when the script lives on the worker host. */
    private final String sourceCodePath;

    /** Static user configuration injected into the Python runtime context. */
    private final Map<String, Object> scriptConfig;

    /** Output columns expected from the Python script. */
    private final List<PythonColumnConfig> columnConfigs;

    /**
     * Creates an immutable Python transform configuration snapshot.
     *
     * @param errorHandleWay row-level error handling mode
     * @param pythonExecutable python binary used to start the worker
     * @param sourceCode inline script body
     * @param sourceCodePath runtime path of the external script
     * @param scriptConfig static script context
     * @param columnConfigs declared output columns
     */
    public PythonTransformConfig(
            ErrorHandleWay errorHandleWay,
            String pythonExecutable,
            String sourceCode,
            String sourceCodePath,
            Map<String, Object> scriptConfig,
            List<PythonColumnConfig> columnConfigs) {
        this.errorHandleWay = errorHandleWay;
        this.pythonExecutable = pythonExecutable;
        this.sourceCode = sourceCode;
        this.sourceCodePath = sourceCodePath;
        this.scriptConfig = scriptConfig;
        this.columnConfigs = columnConfigs;
    }

    /**
     * Parses the raw transform options and validates the script source contract.
     *
     * @param config readonly transform config
     * @return normalized configuration used by the runtime
     */
    public static PythonTransformConfig of(ReadonlyConfig config) {
        boolean hasSourceCode = config.toConfig().hasPath(SOURCE_CODE.key());
        boolean hasSourceCodePath = config.toConfig().hasPath(SOURCE_CODE_PATH.key());
        String sourceCode = hasSourceCode ? config.get(SOURCE_CODE) : null;
        String sourceCodePath = hasSourceCodePath ? config.get(SOURCE_CODE_PATH) : null;

        boolean validInline = StringUtils.isNotBlank(sourceCode);
        boolean validPath = StringUtils.isNotBlank(sourceCodePath);
        if (validInline == validPath) {
            throw new TransformException(
                    PYTHON_SCRIPT_MUST_BE_CONFIGURED,
                    PYTHON_SCRIPT_MUST_BE_CONFIGURED.getDescription());
        }

        if (!config.toConfig().hasPath(COLUMNS.key())) {
            throw new TransformException(
                    COLUMNS_MUST_NOT_EMPTY, COLUMNS_MUST_NOT_EMPTY.getDescription());
        }

        List<Map<String, String>> rawColumns = config.get(COLUMNS);
        if (rawColumns == null || rawColumns.isEmpty()) {
            throw new TransformException(
                    COLUMNS_MUST_NOT_EMPTY, COLUMNS_MUST_NOT_EMPTY.getDescription());
        }

        List<PythonColumnConfig> columns = parseColumns(rawColumns);
        Map<String, Object> scriptConfig =
                new LinkedHashMap<>(
                        config.getOptional(SCRIPT_CONFIG).orElse(Collections.emptyMap()));

        ErrorHandleWay errorHandleWay =
                config.get(TransformCommonOptions.ROW_ERROR_HANDLE_WAY_OPTION);
        if (errorHandleWay != ErrorHandleWay.FAIL && errorHandleWay != ErrorHandleWay.SKIP) {
            throw new TransformException(
                    UNSUPPORTED_ERROR_HANDLE_WAY,
                    UNSUPPORTED_ERROR_HANDLE_WAY.getDescription() + ": " + errorHandleWay);
        }

        return new PythonTransformConfig(
                errorHandleWay,
                config.get(PYTHON_EXECUTABLE),
                validInline ? sourceCode : null,
                validPath ? sourceCodePath : null,
                Collections.unmodifiableMap(scriptConfig),
                Collections.unmodifiableList(columns));
    }

    /**
     * Converts the raw column config into schema-aware output column descriptors.
     *
     * @param rawColumns raw column definitions from the job config
     * @return normalized output column definitions
     */
    private static List<PythonColumnConfig> parseColumns(List<Map<String, String>> rawColumns) {
        List<PythonColumnConfig> columns = new ArrayList<>(rawColumns.size());
        Set<String> destFields = new HashSet<>();
        for (Map<String, String> rawColumn : rawColumns) {
            String destField = rawColumn.get(DEST_FIELD.key());
            if (StringUtils.isBlank(destField)) {
                throw new TransformException(
                        DEST_FIELD_MUST_NOT_EMPTY, DEST_FIELD_MUST_NOT_EMPTY.getDescription());
            }
            if (!destFields.add(destField)) {
                throw new TransformException(
                        DUPLICATE_DEST_FIELD_ERROR,
                        DUPLICATE_DEST_FIELD_ERROR.getDescription() + ": " + destField);
            }

            String destType =
                    Optional.ofNullable(rawColumn.get(DEST_TYPE.key()))
                            .filter(StringUtils::isNotBlank)
                            .orElse(DEST_TYPE.defaultValue());
            SeaTunnelDataType<?> dataType =
                    SeaTunnelDataTypeConvertorUtil.deserializeSeaTunnelDataType(
                            destField, destType);
            Column destColumn =
                    PhysicalColumn.of(destField, dataType, (Long) null, true, null, null);
            columns.add(new PythonColumnConfig(destField, destColumn));
        }
        return columns;
    }
}
