<?xml version="1.0" encoding="UTF-8"?>
<!--
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at
       http://www.apache.org/licenses/LICENSE-2.0
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.apache.seatunnel</groupId>
        <artifactId>seatunnel-e2e</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>seatunnel-connector-v2-e2e</artifactId>
    <packaging>pom</packaging>
    <name>SeaTunnel : E2E : Connector V2 :</name>

    <modules>
        <module>connector-assert-e2e</module>
        <module>connector-jdbc-e2e</module>
        <module>connector-redis-e2e</module>
        <module>connector-cdc-db2-e2e</module>
        <module>connector-cdc-sqlserver-e2e</module>
        <module>connector-clickhouse-e2e</module>
        <module>connector-databend-e2e</module>
        <module>connector-starrocks-e2e</module>
        <module>connector-influxdb-e2e</module>
        <module>connector-amazondynamodb-e2e</module>
        <module>connector-amazondocumentdb-e2e</module>
        <module>connector-azurecosmosdb-e2e</module>
        <module>connector-amazonsqs-e2e</module>
        <module>connector-file-local-e2e</module>
        <module>connector-file-cos-e2e</module>
        <module>connector-file-bos-e2e</module>
        <module>connector-file-hadoop-e2e</module>
        <module>connector-file-sftp-e2e</module>
        <module>connector-file-oss-e2e</module>
        <module>connector-file-s3-e2e</module>
        <module>connector-file-gcs-e2e</module>
        <module>connector-cassandra-e2e</module>
        <module>connector-neo4j-e2e</module>
        <module>connector-http-e2e</module>
        <module>connector-rabbitmq-e2e</module>
        <module>connector-kafka-e2e</module>
        <module>connector-doris-e2e</module>
        <module>connector-fake-e2e</module>
        <module>connector-elasticsearch-e2e</module>
        <module>connector-iotdb-e2e</module>
        <module>connector-iotdb-v2-e2e</module>
        <module>connector-cdc-mysql-e2e</module>
        <module>connector-cdc-mongodb-e2e</module>
        <module>connector-iceberg-e2e</module>
        <module>connector-iceberg-hadoop3-e2e</module>
        <module>connector-iceberg-s3-e2e</module>
        <module>connector-tdengine-e2e</module>
        <module>connector-datahub-e2e</module>
        <module>connector-mongodb-e2e</module>
        <module>connector-mqtt-e2e</module>
        <module>connector-hbase-e2e</module>
        <module>connector-web3j-e2e</module>
        <module>connector-maxcompute-e2e</module>
        <module>connector-druid-e2e</module>
        <module>connector-google-firestore-e2e</module>
        <module>connector-google-pubsub-e2e</module>
        <module>connector-azure-queue-storage-e2e</module>
        <module>connector-rocketmq-e2e</module>
        <!--        <module>connector-file-obs-e2e</module>-->
        <module>connector-file-ftp-e2e</module>
        <module>connector-pulsar-e2e</module>
        <module>connector-python-e2e</module>
        <module>connector-paimon-e2e</module>
        <module>connector-kudu-e2e</module>
        <module>connector-easysearch-e2e</module>
        <module>connector-cdc-postgres-e2e</module>
        <module>connector-cdc-oracle-e2e</module>
        <module>connector-hive-e2e</module>
        <module>connector-hudi-e2e</module>
        <module>connector-milvus-e2e</module>
        <module>connector-activemq-e2e</module>
        <module>connector-prometheus-e2e</module>
        <module>connector-qdrant-e2e</module>
        <module>connector-sls-e2e</module>
        <module>connector-socket-e2e</module>
        <module>connector-typesense-e2e</module>
        <module>connector-email-e2e</module>
        <module>connector-edge-socket-e2e</module>
        <module>connector-cdc-opengauss-e2e</module>
        <module>connector-cdc-tidb-e2e</module>
        <module>connector-graphql-e2e</module>
        <module>connector-aerospike-e2e</module>
        <module>connector-sensorsdata-e2e</module>
        <module>connector-hugegraph-e2e</module>
        <module>connector-nebulagraph-e2e</module>
        <module>connector-fluss-e2e</module>
        <module>connector-lance-e2e</module>
        <module>connector-bigquery-e2e</module>
        <module>connector-nats-jetstream-e2e</module>
        <module>connector-couchbase-e2e</module>
        <module>connector-firebase-e2e</module>
    </modules>

    <properties>
        <aliyun.sdk.oss.version>3.4.1</aliyun.sdk.oss.version>
        <aws-java-sdk.version>1.11.271</aws-java-sdk.version>
        <dns-cache-manipulator.version>1.8.0</dns-cache-manipulator.version>
        <hadoop-aliyun.version>3.1.4</hadoop-aliyun.version>
        <hadoop-cos.version>2.6.5-8.0.2</hadoop-cos.version>
        <hive.exec.version>3.1.3</hive.exec.version>
        <jdom.version>1.1</jdom.version>
        <libfb303.version>0.9.3</libfb303.version>
        <mysql.e2e.version>8.0.32</mysql.e2e.version>
        <zstd-jni.version>1.5.5-5</zstd-jni.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.aliyun.oss</groupId>
                <artifactId>aliyun-sdk-oss</artifactId>
                <version>${aliyun.sdk.oss.version}</version>
            </dependency>
            <dependency>
                <groupId>com.amazonaws</groupId>
                <artifactId>aws-java-sdk-bundle</artifactId>
                <version>${aws-java-sdk.version}</version>
            </dependency>
            <dependency>
                <groupId>com.github.luben</groupId>
                <artifactId>zstd-jni</artifactId>
                <version>${zstd-jni.version}</version>
            </dependency>
            <dependency>
                <groupId>com.mysql</groupId>
                <artifactId>mysql-connector-j</artifactId>
                <version>${mysql.e2e.version}</version>
            </dependency>
            <dependency>
                <groupId>com.qcloud.cos</groupId>
                <artifactId>hadoop-cos</artifactId>
                <version>${hadoop-cos.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.hadoop</groupId>
                <artifactId>hadoop-aliyun</artifactId>
                <version>${hadoop-aliyun.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.hadoop</groupId>
                <artifactId>hadoop-aws</artifactId>
                <version>${hadoop-aws.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.thrift</groupId>
                <artifactId>libfb303</artifactId>
                <version>${libfb303.version}</version>
            </dependency>
            <dependency>
                <groupId>org.jdom</groupId>
                <artifactId>jdom</artifactId>
                <version>${jdom.version}</version>
            </dependency>
            <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>dns-cache-manipulator</artifactId>
                <version>${dns-cache-manipulator.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.apache.seatunnel</groupId>
            <artifactId>seatunnel-e2e-common</artifactId>
            <version>${project.version}</version>
            <type>test-jar</type>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.seatunnel</groupId>
            <artifactId>seatunnel-flink-13-starter</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.seatunnel</groupId>
            <artifactId>seatunnel-flink-15-starter</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.seatunnel</groupId>
            <artifactId>seatunnel-flink-20-starter</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.seatunnel</groupId>
            <artifactId>seatunnel-spark-2-starter</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.seatunnel</groupId>
            <artifactId>seatunnel-spark-3-starter</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.seatunnel</groupId>
            <artifactId>seatunnel-starter</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

</project>
