/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.seatunnel.connectors.seatunnel.hudi.sink.state;

import org.apache.hudi.client.WriteStatus;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;
import java.util.List;

/**
 * The information of the Hudi instant that a writer prepared for one checkpoint.
 *
 * <p>With the exactly-once semantics the records are written into an instant while the job is
 * running, and the instant is committed by the aggregated committer only after the checkpoint that
 * contains it completes. Both the instant time and the write statuses are required to commit it, so
 * they are carried by the commit info instead of being regenerated by the committer.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class HudiCommitInfo implements Serializable {

    private static final long serialVersionUID = 981370692566509995L;

    /** The checkpoint the instant belongs to, only used for logging and troubleshooting. */
    private long checkpointId;

    /** The Hudi instant time the records of this checkpoint were written with. */
    private String instantTime;

    /** The write statuses returned by the Hudi write client for this instant. */
    private List<WriteStatus> writeStatuses;
}
