<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.apache.seatunnel</groupId>
        <artifactId>seatunnel-connectors-v2</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>connector-fluss</artifactId>
    <name>SeaTunnel : Connectors V2 : Fluss</name>

    <properties>
        <fluss.client.version>0.7.0</fluss.client.version>
        <connector.name>connector.fluss</connector.name>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.apache.seatunnel</groupId>
            <artifactId>seatunnel-api</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.seatunnel</groupId>
            <artifactId>connector-common</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.alibaba.fluss</groupId>
            <artifactId>fluss-client</artifactId>
            <version>${fluss.client.version}</version>
        </dependency>
    </dependencies>

</project>
