/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.seatunnel.connectors.seatunnel.file.sink.config;

import org.apache.seatunnel.shade.org.apache.commons.lang3.StringUtils;

import org.apache.seatunnel.api.configuration.ReadonlyConfig;
import org.apache.seatunnel.api.table.type.SeaTunnelRowType;
import org.apache.seatunnel.common.exception.CommonErrorCodeDeprecated;
import org.apache.seatunnel.connectors.seatunnel.file.config.BaseFileSinkConfig;
import org.apache.seatunnel.connectors.seatunnel.file.config.FileBaseSinkOptions;
import org.apache.seatunnel.connectors.seatunnel.file.config.FileFormat;
import org.apache.seatunnel.connectors.seatunnel.file.config.PartitionConfig;
import org.apache.seatunnel.connectors.seatunnel.file.exception.FileConnectorException;
import org.apache.seatunnel.format.csv.constant.CsvStringQuoteMode;

import org.apache.commons.collections4.CollectionUtils;

import lombok.Data;
import lombok.NonNull;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

import static org.apache.seatunnel.shade.com.google.common.base.Preconditions.checkArgument;

@Data
public class FileSinkConfig extends BaseFileSinkConfig implements PartitionConfig {

    private List<String> sinkColumnList;

    private List<String> partitionFieldList;

    private String partitionDirExpression;

    private boolean isPartitionFieldWriteInFile;

    private String tmpPath;

    private String fileNameTimeFormat;

    private boolean isEnableTransaction;

    private String encoding;

    // ---------------------generator by config params-------------------

    private List<Integer> sinkColumnsIndexInRow;

    private List<Integer> partitionFieldsIndexInRow;

    private int maxRowsInMemory;

    private String sheetName;

    private String xmlRootTag;

    private String xmlRowTag;

    private Boolean xmlUseAttrFormat;

    private Boolean parquetWriteTimestampAsInt96;

    private List<String> parquetAvroWriteFixedAsInt96;

    private CsvStringQuoteMode csvStringQuoteMode;

    private Boolean mergeUpdateEvent;

    public FileSinkConfig(
            @NonNull ReadonlyConfig pluginConfig, @NonNull SeaTunnelRowType seaTunnelRowTypeInfo) {
        super(pluginConfig);
        checkArgument(
                !CollectionUtils.isEmpty(Arrays.asList(seaTunnelRowTypeInfo.getFieldNames())));

        if (pluginConfig.getOptional(FileBaseSinkOptions.SINK_COLUMNS).isPresent()) {
            this.sinkColumnList = pluginConfig.get(FileBaseSinkOptions.SINK_COLUMNS);
        }

        // if the config sink_columns is empty, all fields in SeaTunnelRowTypeInfo will being write
        if (CollectionUtils.isEmpty(this.sinkColumnList)) {
            // construct a new ArrayList, because `list` generated by `Arrays.asList` do not support
            // remove and add operations.
            this.sinkColumnList =
                    new ArrayList<>(Arrays.asList(seaTunnelRowTypeInfo.getFieldNames()));
        }

        if (pluginConfig.getOptional(FileBaseSinkOptions.PARTITION_BY).isPresent()) {
            this.partitionFieldList = pluginConfig.get(FileBaseSinkOptions.PARTITION_BY);
        } else {
            this.partitionFieldList = Collections.emptyList();
        }

        if (pluginConfig.getOptional(FileBaseSinkOptions.PARTITION_DIR_EXPRESSION).isPresent()
                && !StringUtils.isBlank(
                        pluginConfig.get(FileBaseSinkOptions.PARTITION_DIR_EXPRESSION))) {
            this.partitionDirExpression =
                    pluginConfig.get(FileBaseSinkOptions.PARTITION_DIR_EXPRESSION);
        }

        this.isPartitionFieldWriteInFile =
                pluginConfig.get(FileBaseSinkOptions.IS_PARTITION_FIELD_WRITE_IN_FILE);

        this.tmpPath = pluginConfig.get(FileBaseSinkOptions.TMP_PATH);

        this.fileNameTimeFormat = pluginConfig.get(FileBaseSinkOptions.FILENAME_TIME_FORMAT);
        this.isEnableTransaction = pluginConfig.get(FileBaseSinkOptions.IS_ENABLE_TRANSACTION);
        this.encoding = pluginConfig.get(FileBaseSinkOptions.ENCODING);

        if (this.isEnableTransaction
                && !this.fileNameExpression.contains(FileBaseSinkOptions.TRANSACTION_EXPRESSION)) {
            throw new FileConnectorException(
                    CommonErrorCodeDeprecated.ILLEGAL_ARGUMENT,
                    "file_name_expression must contains "
                            + FileBaseSinkOptions.TRANSACTION_EXPRESSION
                            + " when is_enable_transaction is true");
        }

        // check partition field must in seaTunnelRowTypeInfo
        if (!CollectionUtils.isEmpty(this.partitionFieldList)
                && (CollectionUtils.isEmpty(this.sinkColumnList)
                        || !new HashSet<>(this.sinkColumnList)
                                .containsAll(this.partitionFieldList))) {
            throw new FileConnectorException(
                    CommonErrorCodeDeprecated.ILLEGAL_ARGUMENT,
                    "partition fields must in sink columns");
        }

        if (!CollectionUtils.isEmpty(this.partitionFieldList) && !isPartitionFieldWriteInFile) {
            if (!this.sinkColumnList.removeAll(this.partitionFieldList)) {
                throw new FileConnectorException(
                        CommonErrorCodeDeprecated.ILLEGAL_ARGUMENT,
                        "remove partition field from sink columns error");
            }
        }

        if (CollectionUtils.isEmpty(this.sinkColumnList)) {
            throw new FileConnectorException(
                    CommonErrorCodeDeprecated.ILLEGAL_ARGUMENT, "sink columns can not be empty");
        }

        Map<String, Integer> columnsMap =
                new HashMap<>(seaTunnelRowTypeInfo.getFieldNames().length);
        String[] fieldNames = seaTunnelRowTypeInfo.getFieldNames();
        for (int i = 0; i < fieldNames.length; i++) {
            columnsMap.put(fieldNames[i].toLowerCase(), i);
        }

        // init sink column index and partition field index, we will use the column index to found
        // the data in SeaTunnelRow
        this.sinkColumnsIndexInRow =
                this.sinkColumnList.stream()
                        .map(column -> columnsMap.get(column.toLowerCase()))
                        .filter(e -> e != null)
                        .collect(Collectors.toList());

        if (!CollectionUtils.isEmpty(this.partitionFieldList)) {
            this.partitionFieldsIndexInRow =
                    this.partitionFieldList.stream()
                            .map(columnsMap::get)
                            .collect(Collectors.toList());
        }

        if (pluginConfig.getOptional(FileBaseSinkOptions.MAX_ROWS_IN_MEMORY).isPresent()) {
            this.maxRowsInMemory = pluginConfig.get(FileBaseSinkOptions.MAX_ROWS_IN_MEMORY);
        }

        if (pluginConfig.getOptional(FileBaseSinkOptions.SHEET_NAME).isPresent()) {
            this.sheetName = pluginConfig.get(FileBaseSinkOptions.SHEET_NAME);
        }

        if (FileFormat.XML.equals(this.fileFormat)) {
            if (!pluginConfig.getOptional(FileBaseSinkOptions.XML_USE_ATTR_FORMAT).isPresent()) {
                throw new FileConnectorException(
                        CommonErrorCodeDeprecated.ILLEGAL_ARGUMENT,
                        "User must define xml_use_attr_format when file_format_type is xml");
            }

            this.xmlUseAttrFormat = pluginConfig.get(FileBaseSinkOptions.XML_USE_ATTR_FORMAT);
            this.xmlRootTag = pluginConfig.get(FileBaseSinkOptions.XML_ROOT_TAG);
            this.xmlRowTag = pluginConfig.get(FileBaseSinkOptions.XML_ROW_TAG);
        }

        if (FileFormat.PARQUET.equals(this.fileFormat)) {
            this.parquetWriteTimestampAsInt96 =
                    pluginConfig.get(FileBaseSinkOptions.PARQUET_AVRO_WRITE_TIMESTAMP_AS_INT96);
            this.parquetAvroWriteFixedAsInt96 =
                    pluginConfig.get(FileBaseSinkOptions.PARQUET_AVRO_WRITE_FIXED_AS_INT96);
        }

        if (FileFormat.CSV.equals(this.fileFormat)) {
            this.csvStringQuoteMode = pluginConfig.get(FileBaseSinkOptions.CSV_STRING_QUOTE_MODE);
        }
        if (FileFormat.DEBEZIUM_JSON.equals(this.fileFormat)
                || FileFormat.CANAL_JSON.equals(this.fileFormat)
                || FileFormat.MAXWELL_JSON.equals(this.fileFormat)) {
            this.mergeUpdateEvent = pluginConfig.get(FileBaseSinkOptions.MERGE_UPDATE_EVENT);
        }
    }
}
