<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.apache.seatunnel</groupId>
    <artifactId>seatunnel-connector-v2-e2e</artifactId>
    <version>${revision}</version>
  </parent>

  <artifactId>connector-selectdb-cloud-e2e</artifactId>
  <name>SeaTunnel : E2E : Connector V2 : SelectDB Cloud</name>

  <properties>
    <mysql.version>8.0.31</mysql.version>
  </properties>

  <dependencies>
    <!-- SeaTunnel connectors -->
    <dependency>
      <groupId>org.apache.seatunnel</groupId>
      <artifactId>connector-doris</artifactId>
      <version>${project.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.apache.seatunnel</groupId>
      <artifactId>connector-fake</artifactId>
      <version>${project.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>mysql</groupId>
      <artifactId>mysql-connector-java</artifactId>
      <version>${mysql.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.apache.seatunnel</groupId>
      <artifactId>connector-cdc-mysql</artifactId>
      <version>${project.version}</version>
      <type>test-jar</type>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.apache.seatunnel</groupId>
      <artifactId>connector-assert</artifactId>
      <version>${project.version}</version>
      <scope>test</scope>
    </dependency>
    <!-- test dependencies on TestContainers -->
    <dependency>
      <groupId>org.testcontainers</groupId>
      <artifactId>mysql</artifactId>
      <version>${testcontainer.version}</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
</project>
