env {
"job.mode"="BATCH"
"job.name"="10"
}
source {
        Jdbc {
        metadata_datasource_id = "mysql-221-13307"
        query="SELECT `id`,`name`,`gender`,`birth_date`,`id_number`,`phone_number`,`email`,`home_address`,`marital_status`,`education`,`major`,`graduate_school`,`work_experience`,`position`,`company_name`,`join_date`,`leave_date`,`monthly_salary`,`social_security_number`,`emergency_contact`,`emergency_contact_phone`,`is_party_member`,`health_status`,`height`,`weight`,`blood_type`,`household_registration_address`,`current_address`,`hobbies`,`remarks`,`is_employed`,`employee_number`,`department`,`work_location`,`bank_account_number`,`bank_name`,`skills`,`certificates`,`social_media_account`,`created_at`,`updated_at` FROM `qjq`.`personnel_information_1000w` WHERE 1=1  AND id < 100000 and id > 10"

        }


}
transform {
}
sink {
        Jdbc {
            metadata_datasource_id = "mysql-221-13307"
            generate_sink_sql = true
            database = qjq
            table = personnel_information_1000w_temo
        }
}
