<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Licensed to the Apache Software Foundation (ASF) under one or more
  ~ contributor license agreements.  See the NOTICE file distributed with
  ~ this work for additional information regarding copyright ownership.
  ~ The ASF licenses this file to You under the Apache License, Version 2.0
  ~ (the "License"); you may not use this file except in compliance with
  ~ the License.  You may obtain a copy of the License at
  ~
  ~    http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.apache.seatunnel</groupId>
        <artifactId>seatunnel-resource-managers</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <artifactId>seatunnel-resource-manager-kubernetes</artifactId>
    <name>SeaTunnel : Resource Managers : Kubernetes</name>
    <dependencies>
        <dependency>
            <groupId>org.apache.seatunnel</groupId>
            <artifactId>seatunnel-resource-manager-core</artifactId>
            <version>${project.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.seatunnel</groupId>
            <artifactId>seatunnel-engine-common</artifactId>
            <version>${project.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.seatunnel</groupId>
            <artifactId>seatunnel-starter</artifactId>
            <version>${project.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>io.kubernetes</groupId>
            <artifactId>client-java</artifactId>
            <version>19.0.1</version>
            <exclusions>
                <exclusion>
                    <groupId>com.squareup.okhttp3</groupId>
                    <artifactId>okhttp</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.squareup.okhttp3</groupId>
                    <artifactId>logging-interceptor</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp</artifactId>
        </dependency>
        <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>logging-interceptor</artifactId>
            <version>${okhttp.version}</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <configuration>
                    <artifactSet>
                        <excludes>
                            <exclude>org.slf4j:*</exclude>
                            <exclude>ch.qos.logback:*</exclude>
                            <exclude>log4j:*</exclude>
                            <exclude>org.apache.logging.log4j:*</exclude>
                            <exclude>commons-logging:*</exclude>
                        </excludes>
                    </artifactSet>
                    <relocations>
                        <relocation>
                            <pattern>io.kubernetes</pattern>
                            <shadedPattern>org.apache.seatunnel.resource.kubernetes.shaded.io.kubernetes</shadedPattern>
                        </relocation>
                        <relocation>
                            <pattern>okhttp3</pattern>
                            <shadedPattern>org.apache.seatunnel.resource.kubernetes.shaded.okhttp3</shadedPattern>
                        </relocation>
                        <relocation>
                            <pattern>okio</pattern>
                            <shadedPattern>org.apache.seatunnel.resource.kubernetes.shaded.okio</shadedPattern>
                        </relocation>
                        <relocation>
                            <pattern>com.google.gson</pattern>
                            <shadedPattern>org.apache.seatunnel.resource.kubernetes.shaded.com.google.gson</shadedPattern>
                        </relocation>
                        <relocation>
                            <pattern>org.yaml</pattern>
                            <shadedPattern>org.apache.seatunnel.resource.kubernetes.shaded.org.yaml</shadedPattern>
                        </relocation>
                        <relocation>
                            <pattern>com.fasterxml.jackson</pattern>
                            <shadedPattern>org.apache.seatunnel.resource.kubernetes.shaded.com.fasterxml.jackson</shadedPattern>
                        </relocation>
                        <relocation>
                            <pattern>com.google.protobuf</pattern>
                            <shadedPattern>org.apache.seatunnel.resource.kubernetes.shaded.com.google.protobuf</shadedPattern>
                        </relocation>
                        <relocation>
                            <pattern>com.google.common</pattern>
                            <shadedPattern>org.apache.seatunnel.resource.kubernetes.shaded.com.google.common</shadedPattern>
                        </relocation>
                        <relocation>
                            <pattern>io.gsonfire</pattern>
                            <shadedPattern>org.apache.seatunnel.resource.kubernetes.shaded.io.gsonfire</shadedPattern>
                        </relocation>
                        <relocation>
                            <pattern>io.prometheus</pattern>
                            <shadedPattern>org.apache.seatunnel.resource.kubernetes.shaded.io.prometheus</shadedPattern>
                        </relocation>
                        <relocation>
                            <pattern>org.apache.commons</pattern>
                            <shadedPattern>org.apache.seatunnel.resource.kubernetes.shaded.org.apache.commons</shadedPattern>
                        </relocation>
                        <relocation>
                            <pattern>org.jose4j</pattern>
                            <shadedPattern>org.apache.seatunnel.resource.kubernetes.shaded.org.jose4j</shadedPattern>
                        </relocation>
                        <relocation>
                            <pattern>org.bouncycastle</pattern>
                            <shadedPattern>org.apache.seatunnel.resource.kubernetes.shaded.org.bouncycastle</shadedPattern>
                        </relocation>
                        <relocation>
                            <pattern>kotlin</pattern>
                            <shadedPattern>org.apache.seatunnel.resource.kubernetes.shaded.kotlin</shadedPattern>
                        </relocation>
                        <relocation>
                            <pattern>org.intellij</pattern>
                            <shadedPattern>org.apache.seatunnel.resource.kubernetes.shaded.org.intellij</shadedPattern>
                        </relocation>
                        <relocation>
                            <pattern>org.jetbrains</pattern>
                            <shadedPattern>org.apache.seatunnel.resource.kubernetes.shaded.org.jetbrains</shadedPattern>
                        </relocation>
                    </relocations>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
