#!/bin/sh
#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
set -

if [ -f "/etc/seatunnel/conf/seatunnel-env.sh" ]; then
    . "/etc/seatunnel/conf/seatunnel-env.sh"
    echo "Using /etc/seatunnel/conf/seatunnel-env.sh."
else
    echo "File /etc/seatunnel/conf/seatunnel-env.sh does not exist."
    exit 1
fi
if [ -z "${APP_DIR}" ]; then
    echo "APP_DIR is not set. It must be set in seatunnel-env.sh"
    exit 1
fi
BIN_DIR="${APP_DIR}/bin"

start() {
  echo "starting seatunnel"
  . "${BIN_DIR}/seatunnel-cluster.sh" -d
  echo "seatunnel started"
}

stop() {
  echo "stopping seatunnel..."
  . "${BIN_DIR}/stop-seatunnel-cluster.sh"
  echo "seatunnel stopped"
}

status() {
  if jcmd | grep -q -i 'org.apache.seatunnel.core.starter.seatunnel.SeaTunnelServer'; then
    echo "seatunnel is running"
  else
    echo "seatunnel is not running"
  fi
}

case "$1" in
  "start") start ;;
  "stop") stop ;;
  "status") status ;;
  *) echo "Usage: seatunnel {start|stop|status}"; exit 1 ;;
esac