{
 "title": "Seatunnel Cluster",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Node Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_count" }
   ]
  },
  {
   "title": "UP Node Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(node_state)" }
   ]
  },
  { "title": "Hazelcast Partition", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "partitionCount",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "hazelcast_partition_partitionCount",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "activePartition",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "hazelcast_partition_activePartition",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "isClusterSafe",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "hazelcast_partition_isClusterSafe",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "isLocalMemberSafe",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "hazelcast_partition_isLocalMemberSafe",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Hazelcast Executor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "executedCount",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "hazelcast_executor_executedCount",
     "legendFormat": "{{instance}}-{{type}}"
    }
   ]
  },
  {
   "title": "isTerminated",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "hazelcast_executor_isTerminated",
     "legendFormat": "{{instance}}-{{type}}"
    }
   ]
  },
  {
   "title": "isShutdown",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    { "expr": "hazelcast_executor_isShutdown", "legendFormat": "{{instance}}-{{type}}" }
   ]
  },
  {
   "title": "poolSize",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    { "expr": "hazelcast_executor_poolSize", "legendFormat": "{{instance}}-{{type}}" }
   ]
  },
  {
   "title": "maxPoolSize",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    { "expr": "hazelcast_executor_maxPoolSize", "legendFormat": "{{instance}}-{{type}}" }
   ]
  },
  {
   "title": "queueRemainingCapacity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "hazelcast_executor_queueRemainingCapacity",
     "legendFormat": "{{instance}}-{{type}}"
    }
   ]
  },
  {
   "title": "queueSize",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    { "expr": "hazelcast_executor_queueSize", "legendFormat": "{{instance}}-{{type}}" }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Cpu Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "100 * (1 - rate(process_cpu_seconds_total[15s]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Heap Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "100 * (jvm_memory_bytes_used{area=\"heap\"} / jvm_memory_bytes_max{area=\"heap\"})",
     "legendFormat": "{{instance}}-{{area}}"
    }
   ]
  },
  {
   "title": "GC Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "round(delta(jvm_gc_collection_seconds_count[15s]))",
     "legendFormat": "{{instance}}-{{gc}}"
    }
   ]
  },
  {
   "title": "GC Cost Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "expr": "delta(jvm_gc_collection_seconds_sum[15s]) * 1000",
     "legendFormat": "{{instance}}-{{gc}}"
    }
   ]
  },
  {
   "title": "Jvm Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 67 },
   "targets": [
    { "expr": "jvm_threads_current", "legendFormat": "{{instance}}-current" },
    { "expr": "jvm_threads_daemon", "legendFormat": "{{instance}}-daemon" },
    { "expr": "jvm_threads_peak", "legendFormat": "{{instance}}-peak" },
    { "expr": "jvm_threads_deadlocked", "legendFormat": "{{instance}}-deadlocked" }
   ]
  },
  { "title": "Job", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "Job Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 76 },
   "targets": [
    { "expr": "sum(job_count) by (type) ", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "Job Thread Pool",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 82 },
   "targets": [
    { "expr": "job_thread_pool_activeCount", "legendFormat": "{{instance}}-activeCount" },
    { "expr": "job_thread_pool_corePoolSize", "legendFormat": "{{instance}}-corePoolSize" },
    { "expr": "job_thread_pool_poolSize", "legendFormat": "{{instance}}-poolSize" }
   ]
  },
  {
   "title": "Job Thread Pool Total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 82 },
   "targets": [
    {
     "expr": "job_thread_pool_completedTask_total",
     "legendFormat": "{{instance}}-completedTaskTotal"
    },
    { "expr": "job_thread_pool_task_total", "legendFormat": "{{instance}}-taskTotal" }
   ]
  }
 ]
}