/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.seatunnel.connectors.seatunnel.cdc.oceanbase;

import org.apache.seatunnel.e2e.common.TestResource;
import org.apache.seatunnel.e2e.common.TestSuiteBase;
import org.apache.seatunnel.e2e.common.container.ContainerExtendedFactory;
import org.apache.seatunnel.e2e.common.container.EngineType;
import org.apache.seatunnel.e2e.common.container.TestContainer;
import org.apache.seatunnel.e2e.common.junit.DisabledOnContainer;
import org.apache.seatunnel.e2e.common.junit.TestContainerExtension;
import org.apache.seatunnel.e2e.common.util.ContainerUtil;

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.TestTemplate;
import org.testcontainers.containers.Container;
import org.testcontainers.containers.output.Slf4jLogConsumer;
import org.testcontainers.lifecycle.Startables;
import org.testcontainers.utility.DockerLoggerFactory;

import lombok.extern.slf4j.Slf4j;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.ObjectOutputStream;
import java.net.URL;
import java.net.URLClassLoader;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionException;
import java.util.concurrent.TimeUnit;
import java.util.stream.Stream;

import static org.awaitility.Awaitility.await;

/**
 * Verifies that the OceanBase CDC connector can be discovered and run through the MySQL-compatible
 * CDC path used by the current OceanBase wrapper.
 *
 * <p>This is intentionally a compatibility smoke E2E. It does not claim to validate a real
 * OceanBase Binlog Service deployment because the project has no reusable OceanBase CDC
 * Testcontainers environment yet.
 */
@Slf4j
@DisabledOnContainer(
        value = {},
        type = {EngineType.SPARK},
        disabledReason = "Currently SPARK do not support cdc")
public class OceanBaseCDCCompatibilityIT extends TestSuiteBase implements TestResource {

    /**
     * Network alias used by SeaTunnel engine containers to reach the MySQL-compatible CDC source.
     */
    private static final String MYSQL_HOST = "mysql_cdc_e2e";

    /** Administrative user used by the test to prepare source and sink tables. */
    private static final String MYSQL_USER_NAME = "mysqluser";

    /** Password shared by the setup SQL users in the MySQL-compatible E2E environment. */
    private static final String MYSQL_USER_PASSWORD = "mysqlpw";

    /** Database name shared with the SeaTunnel job config under test. */
    private static final String MYSQL_DATABASE = "mysql_cdc";

    /** Small source table used to keep the OceanBase wrapper smoke test focused and fast. */
    private static final String SOURCE_TABLE = "oceanbase_cdc_e2e_source_table";

    /** Dedicated sink table generated by the JDBC sink for this compatibility test. */
    private static final String SINK_TABLE = "oceanbase_cdc_e2e_sink_table";

    /** MySQL driver jar required by the OceanBase wrapper because it delegates to MySQL CDC. */
    private static final String MYSQL_DRIVER_URL =
            "https://repo1.maven.org/maven2/com/mysql/mysql-connector-j/8.0.32/mysql-connector-j-8.0.32.jar";

    /** MySQL-compatible source container used as the reproducible CDC runtime for the wrapper. */
    private static final MySqlCompatibleContainer MYSQL_CONTAINER = createMySqlContainer();

    /**
     * Build the MySQL-compatible source with GTID/binlog settings required by CDC readers.
     *
     * @return configured MySQL-compatible container
     */
    private static MySqlCompatibleContainer createMySqlContainer() {
        return new MySqlCompatibleContainer("8.0.43")
                .withConfigurationOverride("docker/server-gtids/my.cnf")
                .withSetupSQL("docker/setup.sql")
                .withNetwork(NETWORK)
                .withNetworkAliases(MYSQL_HOST)
                .withDatabaseName(MYSQL_DATABASE)
                .withUsername(MYSQL_USER_NAME)
                .withPassword(MYSQL_USER_PASSWORD)
                .withLogConsumer(
                        new Slf4jLogConsumer(DockerLoggerFactory.getLogger("mysql-docker-image")));
    }

    /**
     * Install the JDBC driver into the OceanBase CDC plugin directory inside each engine container.
     */
    @TestContainerExtension
    protected final ContainerExtendedFactory extendedFactory =
            container -> {
                Container.ExecResult extraCommands =
                        container.execInContainer(
                                "bash",
                                "-c",
                                "mkdir -p /tmp/seatunnel/plugins/OceanBase-CDC/lib && cd /tmp/seatunnel/plugins/OceanBase-CDC/lib && wget "
                                        + MYSQL_DRIVER_URL);
                Assertions.assertEquals(0, extraCommands.getExitCode(), extraCommands.getStderr());
            };

    /** Start the MySQL-compatible CDC source before the SeaTunnel job containers run. */
    @BeforeAll
    @Override
    public void startUp() {
        log.info("Starting MySQL-compatible container for OceanBase CDC compatibility E2E.");
        Startables.deepStart(Stream.of(MYSQL_CONTAINER)).join();
        log.info("MySQL-compatible container for OceanBase CDC compatibility E2E is started.");
    }

    /** Close the MySQL container allocated by this test class. */
    @Override
    @AfterAll
    public void tearDown() {
        if (MYSQL_CONTAINER != null) {
            MYSQL_CONTAINER.close();
        }
    }

    /**
     * Run OceanBase-CDC against a MySQL-compatible CDC source and verify snapshot plus incremental
     * events reach the JDBC sink.
     *
     * @param container SeaTunnel engine test container
     * @throws Exception if the packaged CDC classes cannot be loaded or serialized
     */
    @TestTemplate
    public void testOceanBaseCdcWrapperRuntimeE2e(TestContainer container) throws Exception {
        assertPackagedTableIdSerialization();
        recreateTestTables();

        CompletableFuture<Void> jobFuture =
                CompletableFuture.runAsync(
                        () -> {
                            try {
                                Container.ExecResult execResult =
                                        container.executeJob(
                                                "/oceanbasecdc_to_mysql_compatible.conf");
                                Assertions.assertEquals(
                                        0, execResult.getExitCode(), execResult.getStderr());
                            } catch (Exception e) {
                                throw new CompletionException(e);
                            }
                        });

        await().atMost(60, TimeUnit.SECONDS)
                .untilAsserted(
                        () -> {
                            assertStreamingJobStillRunning(jobFuture);
                            Assertions.assertIterableEquals(
                                    queryTable(SOURCE_TABLE), queryTable(SINK_TABLE));
                        });

        applyIncrementalChanges();

        await().atMost(60, TimeUnit.SECONDS)
                .untilAsserted(
                        () -> {
                            assertStreamingJobStillRunning(jobFuture);
                            Assertions.assertIterableEquals(
                                    queryTable(SOURCE_TABLE), queryTable(SINK_TABLE));
                        });
    }

    /**
     * Verifies serialization using the shipped connector jars in either discovery order. An
     * isolated loader prevents the test classpath from hiding an unpatched Debezium class in a
     * shaded jar.
     */
    private void assertPackagedTableIdSerialization() throws Exception {
        List<File> connectorJars =
                ContainerUtil.getConnectorFiles(
                        new File(ContainerUtil.PROJECT_ROOT_PATH, "seatunnel-connectors-v2"),
                        Collections.singleton("connector-cdc-oceanbase"),
                        "connector-");
        Assertions.assertEquals(
                2, connectorJars.size(), "Expected OceanBase CDC and CDC base artifacts");
        assertTableIdSerialization(connectorJars);
        Collections.reverse(connectorJars);
        assertTableIdSerialization(connectorJars);
    }

    private void assertTableIdSerialization(List<File> connectorJars) throws Exception {
        URL[] urls = new URL[connectorJars.size()];
        for (int index = 0; index < connectorJars.size(); index++) {
            urls[index] = connectorJars.get(index).toURI().toURL();
        }
        try (URLClassLoader loader = new URLClassLoader(urls, null);
                ObjectOutputStream output = new ObjectOutputStream(new ByteArrayOutputStream())) {
            Object tableId =
                    loader.loadClass("io.debezium.relational.TableId")
                            .getConstructor(String.class, String.class, String.class)
                            .newInstance(MYSQL_DATABASE, null, SOURCE_TABLE);
            Assertions.assertDoesNotThrow(
                    () -> output.writeObject(tableId),
                    "Packaged TableId must serialize for connector order: " + connectorJars);
        }
    }

    /** Recreate isolated source and sink tables for deterministic snapshot assertions. */
    private void recreateTestTables() {
        executeSql("DROP TABLE IF EXISTS " + MYSQL_DATABASE + "." + SINK_TABLE);
        executeSql("DROP TABLE IF EXISTS " + MYSQL_DATABASE + "." + SOURCE_TABLE);
        executeSql(
                "CREATE TABLE "
                        + MYSQL_DATABASE
                        + "."
                        + SOURCE_TABLE
                        + " (id INT PRIMARY KEY, name VARCHAR(64), score INT)");
        executeSql(
                "CREATE TABLE "
                        + MYSQL_DATABASE
                        + "."
                        + SINK_TABLE
                        + " (id INT PRIMARY KEY, name VARCHAR(64), score INT)");
        executeSql(
                "INSERT INTO "
                        + MYSQL_DATABASE
                        + "."
                        + SOURCE_TABLE
                        + " VALUES (1, 'alpha', 10), (2, 'beta', 20)");
    }

    /** Apply insert, update and delete operations after the initial snapshot is synchronized. */
    private void applyIncrementalChanges() {
        executeSql(
                "INSERT INTO " + MYSQL_DATABASE + "." + SOURCE_TABLE + " VALUES (3, 'gamma', 30)");
        executeSql(
                "UPDATE " + MYSQL_DATABASE + "." + SOURCE_TABLE + " SET score = 25 WHERE id = 2");
        executeSql("DELETE FROM " + MYSQL_DATABASE + "." + SOURCE_TABLE + " WHERE id = 1");
    }

    /**
     * Fail fast if the asynchronous streaming job has already exited or failed.
     *
     * @param jobFuture asynchronous SeaTunnel job execution future
     */
    private void assertStreamingJobStillRunning(CompletableFuture<Void> jobFuture) {
        if (jobFuture.isCompletedExceptionally()) {
            jobFuture.join();
        }
        Assertions.assertFalse(jobFuture.isDone(), "OceanBase CDC streaming job exited early.");
    }

    /**
     * Query the deterministic table projection used by this test.
     *
     * @param tableName source or sink table name
     * @return rows ordered by primary key
     */
    private List<List<Object>> queryTable(String tableName) {
        String sql =
                "SELECT id, name, score FROM " + MYSQL_DATABASE + "." + tableName + " ORDER BY id";
        try (Connection connection = getJdbcConnection();
                Statement statement = connection.createStatement();
                ResultSet resultSet = statement.executeQuery(sql)) {
            List<List<Object>> result = new ArrayList<>();
            while (resultSet.next()) {
                result.add(
                        Arrays.asList(
                                resultSet.getInt("id"),
                                resultSet.getString("name"),
                                resultSet.getInt("score")));
            }
            log.debug("OceanBase CDC compatibility query, sql: {}, data: {}", sql, result);
            return result;
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    /**
     * Execute table setup and mutation SQL against the MySQL-compatible CDC source.
     *
     * @param sql SQL statement to execute
     */
    private void executeSql(String sql) {
        try (Connection connection = getJdbcConnection();
                Statement statement = connection.createStatement()) {
            statement.execute(sql);
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    /**
     * Open an administrative JDBC connection to the MySQL-compatible source container.
     *
     * @return JDBC connection for setup and assertions
     * @throws SQLException when the container rejects the connection
     */
    private Connection getJdbcConnection() throws SQLException {
        return DriverManager.getConnection(
                MYSQL_CONTAINER.getJdbcUrl(),
                MYSQL_CONTAINER.getUsername(),
                MYSQL_CONTAINER.getPassword());
    }
}
