#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

"""Three-tier connector knowledge base with runtime API support.

Data sources (in priority order):
  1. Runtime API  — GET /option-rules?type=source&plugin=Jdbc
                    Live from running SeaTunnel engine. Always accurate, zero maintenance.
  2. Static JSON  — connector_catalog.json (generated by build_catalog.py)
                    Offline fallback. Needs regeneration when connectors change.

Retrieval tiers:
  L1 (Index)  — Compact list of all connectors (~1800 tokens). Always in system prompt.
  L2 (Detail) — Full options per connector. On-demand via get_connector_info tool.
                Tries runtime API first, falls back to static JSON.

Keyword routing:
  User says "mysql" → routes to ["Jdbc", "MySQL-CDC"]
  User says "s3"    → routes to ["S3File", "S3Redshift"]
"""

import json
import logging
import os
import time
import urllib.request
import urllib.error
from pathlib import Path

logger = logging.getLogger(__name__)

# ─── Runtime API client ───

# Default REST API base — SeaTunnel engine HTTP port.
# In cluster mode (seatunnel-server.sh): REST API on port 5801 by default.
# In local mode (-m local): REST API is NOT available.
# Users can override with SEATUNNEL_API_BASE env var.
_ENGINE_API_BASE = os.environ.get("SEATUNNEL_API_BASE", "http://localhost:5801")
_API_CACHE: dict[str, dict] = {}  # memory cache: "source:Jdbc" → parsed response
_ENGINE_AVAILABLE: bool | None = None  # None = not checked yet
_ENGINE_CHECK_TS: float = 0  # timestamp of last check — recheck after 60s

# Disk cache directory for offline reuse of runtime API responses
_DISK_CACHE_DIR = Path.home() / ".seatunnel" / "api_cache"


def _check_engine() -> bool:
    """Check if SeaTunnel engine REST API is reachable.

    Re-checks every 60 seconds so a newly started engine is detected mid-session.
    """
    global _ENGINE_AVAILABLE, _ENGINE_CHECK_TS
    now = time.monotonic()
    if _ENGINE_AVAILABLE is not None and (now - _ENGINE_CHECK_TS) < 60:
        return _ENGINE_AVAILABLE
    try:
        req = urllib.request.Request(f"{_ENGINE_API_BASE}/running-jobs", method="GET")
        with urllib.request.urlopen(req, timeout=2) as resp:
            _ENGINE_AVAILABLE = resp.status == 200
    except Exception:
        _ENGINE_AVAILABLE = False
    _ENGINE_CHECK_TS = now
    return _ENGINE_AVAILABLE


def _read_disk_cache(cache_key: str) -> dict | None:
    """Read a cached API response from disk."""
    path = _DISK_CACHE_DIR / f"{cache_key.replace(':', '_')}.json"
    if path.exists():
        try:
            with open(path, "r", encoding="utf-8") as f:
                return json.load(f)
        except Exception:
            pass
    return None


def _write_disk_cache(cache_key: str, data: dict):
    """Write an API response to disk cache for offline reuse."""
    try:
        _DISK_CACHE_DIR.mkdir(parents=True, exist_ok=True)
        path = _DISK_CACHE_DIR / f"{cache_key.replace(':', '_')}.json"
        with open(path, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2)
    except Exception as e:
        logger.debug(f"Failed to write disk cache for {cache_key}: {e}")


def _fetch_option_rules(plugin_type: str, plugin_name: str) -> dict | None:
    """Fetch option rules from running SeaTunnel engine.

    GET /option-rules?type=source&plugin=FakeSource
    Returns parsed JSON response or None if unavailable.

    Resolution order:
      1. In-memory cache (fastest)
      2. Live API call (authoritative)
      3. Disk cache (offline fallback from previous session)
    """
    cache_key = f"{plugin_type}:{plugin_name}"

    # 1. Memory cache
    if cache_key in _API_CACHE:
        return _API_CACHE[cache_key]

    # 2. Live API
    if _check_engine():
        try:
            url = f"{_ENGINE_API_BASE}/option-rules?type={plugin_type}&plugin={plugin_name}"
            req = urllib.request.Request(url, method="GET")
            with urllib.request.urlopen(req, timeout=5) as resp:
                if resp.status == 200:
                    data = json.loads(resp.read().decode("utf-8"))
                    _API_CACHE[cache_key] = data
                    _write_disk_cache(cache_key, data)
                    return data
        except Exception as e:
            logger.debug(f"option-rules API call failed for {cache_key}: {e}")

    # 3. Disk cache (from a previous session when engine was online)
    disk_data = _read_disk_cache(cache_key)
    if disk_data:
        _API_CACHE[cache_key] = disk_data
        return disk_data

    return None


def _api_response_to_detail(resp: dict) -> dict:
    """Convert /option-rules API response to our internal detail format."""
    rule = resp.get("optionRule", {})

    required = []
    for req_opt in rule.get("requiredOptions", []):
        rule_type = req_opt.get("ruleType", "")
        for opt in req_opt.get("options", []):
            required.append(_api_opt_to_dict(opt, rule_type=rule_type))

    optional = []
    for opt in rule.get("optionalOptions", []):
        optional.append(_api_opt_to_dict(opt))

    conditional = []
    for cond in rule.get("conditionRules", []):
        expr = cond.get("expression", "")
        nested_rule = cond.get("optionRule", {})
        nested_opts = []
        for req_opt in nested_rule.get("requiredOptions", []):
            for opt in req_opt.get("options", []):
                nested_opts.append(opt.get("key", ""))
        if expr and nested_opts:
            conditional.append({
                "when": expr,
                "equals": "",
                "then_require": nested_opts,
            })

    return {
        "name": resp.get("pluginName", ""),
        "types": [resp.get("pluginType", "unknown")],
        "required": required,
        "optional": optional,
        "exclusive": [],
        "conditional": conditional,
        "examples": [],
        "source": "runtime_api",
    }


def _api_opt_to_dict(opt: dict, rule_type: str = "") -> dict:
    """Convert a single option from API response to our format."""
    result = {"key": opt.get("key", "")}
    java_type = opt.get("type", "")
    if java_type:
        # Simplify: "java.lang.String" → "string"
        simple = java_type.rsplit(".", 1)[-1].lower()
        result["type"] = simple
    default = opt.get("defaultValue")
    if default is not None:
        result["default"] = str(default)
    desc = opt.get("description", "")
    if desc:
        result["description"] = desc[:200]
    if rule_type:
        result["rule_type"] = rule_type
    values = opt.get("optionValues")
    if values:
        result["allowed_values"] = values
    return result


# ─── Static catalog ───

_CATALOG: dict | None = None
_BUNDLED_CATALOG_PATH = Path(__file__).parent / "connector_catalog.json"


def ensure_catalog(quiet: bool = False) -> dict:
    """Load the built-in connector catalog (shipped with the package).

    For install-only users this is the single source of connector knowledge.
    Developers who need a more accurate catalog can run `sync_catalog()`.
    """
    global _CATALOG
    if _CATALOG is not None:
        return _CATALOG

    if _BUNDLED_CATALOG_PATH.exists():
        with open(_BUNDLED_CATALOG_PATH, "r", encoding="utf-8") as f:
            _CATALOG = json.load(f)
        if not quiet:
            logger.info(f"Loaded catalog: {len(_CATALOG['index'])} connectors")
        return _CATALOG

    _CATALOG = {"index": [], "connectors": {}}
    return _CATALOG


def sync_catalog(seatunnel_source: str | Path) -> dict:
    """Full sync: regenerate catalog from SeaTunnel source and update the bundled file.

    Usage:
        seatunnel --sync-catalog /path/to/seatunnel

    This scans the Java source code and overwrites connector_catalog.json
    so future runs (and all users of this installation) get the updated version.
    """
    global _CATALOG
    source_root = Path(seatunnel_source)

    if not (source_root / "seatunnel-connectors-v2").is_dir():
        raise FileNotFoundError(
            f"Not a valid SeaTunnel source: {source_root}\n"
            f"Expected directory: {source_root}/seatunnel-connectors-v2/"
        )

    from .build_catalog import build_catalog
    _CATALOG = build_catalog(source_root, quiet=False)

    with open(_BUNDLED_CATALOG_PATH, "w", encoding="utf-8") as f:
        json.dump(_CATALOG, f, indent=2, ensure_ascii=False)

    count = len(_CATALOG["index"])
    print(f"\nCatalog synced: {count} connectors → {_BUNDLED_CATALOG_PATH}")
    return _CATALOG


def _load_catalog() -> dict:
    """Load the connector catalog."""
    return ensure_catalog(quiet=True)


# ─── Keyword routing: maps user terms → connector names ───

KEYWORD_ALIASES: dict[str, list[str]] = {
    # Databases
    "mysql": ["Jdbc", "MySQL-CDC"],
    "postgres": ["Jdbc", "PostgreSQL-CDC"],
    "postgresql": ["Jdbc", "PostgreSQL-CDC"],
    "oracle": ["Jdbc", "Oracle-CDC"],
    "sqlserver": ["Jdbc", "SqlServer-CDC"],
    "sql server": ["Jdbc", "SqlServer-CDC"],
    "mssql": ["Jdbc", "SqlServer-CDC"],
    "db2": ["Jdbc"],
    "sqlite": ["Jdbc"],
    "dameng": ["Jdbc"],
    "dm": ["Jdbc"],
    "tidb": ["Jdbc", "TiDB-CDC"],
    "mariadb": ["Jdbc"],

    # NoSQL
    "mongo": ["MongoDB", "MongoDB-CDC"],
    "mongodb": ["MongoDB", "MongoDB-CDC"],
    "redis": ["Redis"],
    "cassandra": ["Cassandra"],
    "hbase": ["Hbase"],
    "neo4j": ["Neo4j"],

    # Messaging
    "kafka": ["Kafka"],
    "pulsar": ["Pulsar"],
    "rabbitmq": ["RabbitMQ"],
    "rocketmq": ["RocketMQ"],
    "activemq": ["ActiveMQ"],
    "mqtt": ["Mqtt"],
    "sqs": ["AmazonSqs"],

    # Search
    "elasticsearch": ["Elasticsearch"],
    "es": ["Elasticsearch"],
    "easysearch": ["Easysearch"],

    # File / Object Store
    "s3": ["S3File", "S3Redshift"],
    "hdfs": ["HdfsFile"],
    "local file": ["LocalFile"],
    "csv": ["LocalFile", "S3File", "HdfsFile"],
    "parquet": ["LocalFile", "S3File", "HdfsFile"],
    "json file": ["LocalFile", "S3File", "HdfsFile"],
    "orc": ["LocalFile", "S3File", "HdfsFile"],
    "ftp": ["FtpFile"],
    "sftp": ["SftpFile"],
    "oss": ["OssFile"],

    # OLAP / Data Warehouse
    "clickhouse": ["Clickhouse"],
    "doris": ["Doris"],
    "starrocks": ["StarRocks"],
    "hive": ["Hive"],
    "maxcompute": ["Maxcompute"],
    "redshift": ["S3Redshift"],
    "databend": ["Databend"],

    # Lake
    "iceberg": ["Iceberg"],
    "paimon": ["Paimon"],
    "hudi": ["Hudi"],

    # API
    "http": ["Http"],
    "api": ["Http", "GraphQL"],
    "graphql": ["GraphQL"],
    "webhook": ["Http"],

    # AI / Vector
    "milvus": ["Milvus"],
    "qdrant": ["Qdrant"],
    "pinecone": ["Pinecone"],

    # Other
    "console": ["Console"],
    "fake": ["FakeSource"],
    "test": ["FakeSource", "Console"],
    "dynamodb": ["AmazonDynamoDB"],
    "influxdb": ["InfluxDB"],
    "iotdb": ["IoTDB"],
    "tdengine": ["TDengine"],

    # CDC generic
    "cdc": ["MySQL-CDC", "PostgreSQL-CDC", "Oracle-CDC", "SqlServer-CDC", "MongoDB-CDC", "TiDB-CDC"],
    "binlog": ["MySQL-CDC"],
    "wal": ["PostgreSQL-CDC"],
    "实时同步": ["MySQL-CDC", "PostgreSQL-CDC", "Kafka"],
    "增量": ["MySQL-CDC", "PostgreSQL-CDC", "Jdbc"],
    "全量": ["Jdbc"],
}

# JDBC driver and URL knowledge (enriches Jdbc connector detail)
JDBC_DRIVERS = {
    "mysql": {"driver": "com.mysql.cj.jdbc.Driver", "url": "jdbc:mysql://{host}:{port}/{database}", "port": 3306},
    "postgresql": {"driver": "org.postgresql.Driver", "url": "jdbc:postgresql://{host}:{port}/{database}", "port": 5432},
    "oracle": {"driver": "oracle.jdbc.driver.OracleDriver", "url": "jdbc:oracle:thin:@{host}:{port}:{sid}", "port": 1521},
    "sqlserver": {"driver": "com.microsoft.sqlserver.jdbc.SQLServerDriver", "url": "jdbc:sqlserver://{host}:{port};databaseName={database}", "port": 1433},
    "db2": {"driver": "com.ibm.db2.jcc.DB2Driver", "url": "jdbc:db2://{host}:{port}/{database}", "port": 50000},
    "sqlite": {"driver": "org.sqlite.JDBC", "url": "jdbc:sqlite:{path}", "port": None},
    "dm": {"driver": "dm.jdbc.driver.DmDriver", "url": "jdbc:dm://{host}:{port}", "port": 5236},
}

# ─── Transform plugins (kept inline — small, stable set) ───

TRANSFORMS = {
    "Sql": {
        "description": "Transform data using SQL expressions.",
        "required": ["plugin_input", "plugin_output", "query"],
        "examples": '''Sql {
    plugin_input = "fake"
    plugin_output = "sql_out"
    query = "SELECT id, UPPER(name) as name, age + 1 as age FROM fake WHERE age > 18"
}''',
    },
    "Filter": {
        "description": "Filter rows by condition.",
        "required": ["plugin_input", "plugin_output", "fields"],
        "examples": '''Filter {
    plugin_input = "source"
    plugin_output = "filtered"
    fields = ["id", "name", "age"]
}''',
    },
    "Replace": {
        "description": "Replace field values using regex.",
        "required": ["plugin_input", "plugin_output", "replace_field", "pattern", "replacement"],
        "examples": '''Replace {
    plugin_input = "source"
    plugin_output = "replaced"
    replace_field = "phone"
    pattern = "(\\d{3})\\d{4}(\\d{4})"
    replacement = "$1****$2"
}''',
    },
    "Split": {
        "description": "Split a field into multiple fields.",
        "required": ["plugin_input", "plugin_output", "separator", "split_field"],
        "optional": ["output_fields"],
        "examples": '''Split {
    plugin_input = "source"
    plugin_output = "split_out"
    separator = ","
    split_field = "tags"
    output_fields = ["tag1", "tag2", "tag3"]
}''',
    },
    "FieldMapper": {
        "description": "Rename, remove, or reorder fields.",
        "required": ["plugin_input", "plugin_output", "field_mapper"],
        "examples": '''FieldMapper {
    plugin_input = "source"
    plugin_output = "mapped"
    field_mapper = {
        id = id
        user_name = name
        user_age = age
    }
}''',
    },
    "Copy": {
        "description": "Copy one or more fields to new fields.",
        "required": ["plugin_input", "plugin_output", "fields"],
        "examples": '''Copy {
    plugin_input = "source"
    plugin_output = "copied"
    fields {
        name_backup = "name"
    }
}''',
    },
    "LLM": {
        "description": "Transform data using LLM (Large Language Model) inference.",
        "required": ["plugin_input", "plugin_output", "model_provider", "model", "prompt"],
        "optional": ["openai.api_key", "output_data_type"],
        "examples": '''LLM {
    plugin_input = "source"
    plugin_output = "llm_out"
    model_provider = OPENAI
    model = "gpt-4"
    openai.api_key = "${OPENAI_API_KEY}"
    prompt = "Classify the following text into categories: {{content}}"
    output_data_type = "string"
}''',
    },
    "Embedding": {
        "description": "Generate vector embeddings for text fields.",
        "required": ["plugin_input", "plugin_output", "model_provider", "model", "api_key",
                     "single_vectorized_input_number", "vectorized_fields"],
        "examples": '''Embedding {
    plugin_input = "source"
    plugin_output = "embed_out"
    model_provider = OPENAI
    model = "text-embedding-3-small"
    api_key = "${OPENAI_API_KEY}"
    single_vectorized_input_number = 1
    vectorized_fields {
        content_vector = ["content"]
    }
}''',
    },
}


# ─── Public API ───

def get_connector_catalog() -> str:
    """L1: Build compact connector index for system prompt (~1800 tokens).

    Format:
      - ConnectorName (source, sink) | required: key1, key2 | +N optional
    """
    catalog = _load_catalog()
    engine_status = "connected" if _check_engine() else "offline"
    count = len(catalog["index"])

    lines = [f"## Available Connectors ({count} total) [engine: {engine_status}]\n"]
    lines.append("Use `get_connector_info` tool to get full details for any connector.")
    if engine_status == "connected":
        lines.append("(Details fetched live from running engine — always up-to-date)\n")
    else:
        lines.append("(Details from static catalog — run `python -m seatunnel_cli.build_catalog` to refresh)\n")

    for entry in catalog["index"]:
        types = ", ".join(entry["types"])
        req = ", ".join(entry["required_keys"][:6])
        if len(entry["required_keys"]) > 6:
            req += "..."
        opt_count = entry.get("optional_count", 0)
        lines.append(f"- **{entry['name']}** ({types}) | required: {req or 'none'} | +{opt_count} optional")

    lines.append("\n## Available Transforms\n")
    for name, info in TRANSFORMS.items():
        lines.append(f"- **{name}**: {info['description']}")

    lines.append("\n## JDBC Database Support")
    lines.append("Jdbc connector supports: " + ", ".join(JDBC_DRIVERS.keys()))

    return "\n".join(lines)


def get_connector_detail(name: str) -> str | None:
    """L2: Get full details for one connector (on-demand, via tool call).

    Resolution order:
      1. Runtime /option-rules API (live, always accurate)
      2. Static connector_catalog.json (offline fallback)
      3. Transform plugins (inline dict)
      4. Keyword suggestion

    Returns a formatted string with all options, defaults, conditions, and examples.
    """
    # ── 1. Try runtime API (source + sink) ──
    for plugin_type in ["source", "sink"]:
        api_resp = _fetch_option_rules(plugin_type, name)
        if api_resp:
            detail = _api_response_to_detail(api_resp)
            # Merge examples from static catalog if available
            catalog = _load_catalog()
            static = catalog["connectors"].get(name, {})
            if static.get("examples"):
                detail["examples"] = static["examples"]
            formatted = _format_connector_detail(name, detail)
            return f"[source: runtime API]\n{formatted}"

    # ── 2. Try static catalog ──
    catalog = _load_catalog()
    detail = catalog["connectors"].get(name)

    # Fuzzy match in static catalog
    if not detail:
        name_lower = name.lower().replace("-", "").replace("_", "")
        for k, v in catalog["connectors"].items():
            if k.lower().replace("-", "").replace("_", "") == name_lower:
                detail = v
                name = k
                break

    if detail:
        formatted = _format_connector_detail(name, detail)
        return f"[source: static catalog]\n{formatted}"

    # ── 3. Check transforms ──
    t = TRANSFORMS.get(name)
    if not t:
        for k, v in TRANSFORMS.items():
            if k.lower() == name.lower():
                t = v
                name = k
                break
    if t:
        return _format_transform_detail(name, t)

    # ── 4. Suggest ──
    suggestions = route_by_keyword(name)
    if suggestions:
        return f"Connector '{name}' not found. Did you mean: {', '.join(suggestions)}?\nUse get_connector_info with the exact name."
    return f"Connector '{name}' not found. Use list_connectors to see all available connectors."


def _format_connector_detail(name: str, detail: dict) -> str:
    """Format a connector detail dict into a readable string for the LLM."""
    lines = [f"# {name}"]
    lines.append(f"Types: {', '.join(detail['types'])}\n")

    # Required options
    if detail.get("required"):
        lines.append("## Required Options")
        for opt in detail["required"]:
            desc = opt.get("description", "")
            typ = opt.get("type", "")
            default = opt.get("default")
            line = f"- `{opt['key']}` ({typ})"
            if default is not None:
                line += f" [default: {default}]"
            if desc:
                line += f" — {desc}"
            lines.append(line)

    # Optional options
    if detail.get("optional"):
        lines.append("\n## Optional Options")
        for opt in detail["optional"]:
            desc = opt.get("description", "")
            typ = opt.get("type", "")
            default = opt.get("default")
            line = f"- `{opt['key']}` ({typ})"
            if default is not None:
                line += f" [default: {default}]"
            if desc:
                line += f" — {desc}"
            lines.append(line)

    # Exclusive options
    if detail.get("exclusive"):
        lines.append(f"\n## Mutually Exclusive (pick one): {', '.join(detail['exclusive'])}")

    # Conditional options
    if detail.get("conditional"):
        lines.append("\n## Conditional Options")
        for cond in detail["conditional"]:
            deps = ", ".join(cond["then_require"])
            lines.append(f"- When `{cond['when']}` = `{cond['equals']}` → also require: {deps}")

    # JDBC enrichment
    if name == "Jdbc":
        lines.append("\n## JDBC Driver Reference")
        for db, info in JDBC_DRIVERS.items():
            lines.append(f"- **{db}**: driver=`{info['driver']}` url=`{info['url']}` port={info['port']}")

    # Examples from docs
    if detail.get("examples"):
        lines.append("\n## Config Examples (from docs)")
        for i, ex in enumerate(detail["examples"][:2]):
            lines.append(f"\n### Example {i+1}:")
            lines.append(f"```hocon\n{ex}\n```")

    return "\n".join(lines)


def _format_transform_detail(name: str, info: dict) -> str:
    """Format a transform plugin detail."""
    lines = [f"# Transform: {name}\n", info["description"], ""]
    lines.append(f"**Required**: {', '.join(info['required'])}")
    if info.get("optional"):
        lines.append(f"**Optional**: {', '.join(info['optional'])}")
    examples = info.get("examples", "")
    if examples:
        lines.append(f"\n**Example**:\n```hocon\n{examples}\n```")
    return "\n".join(lines)


def route_by_keyword(user_text: str) -> list[str]:
    """Route user's natural language to relevant connector names.

    Used by PlannerAgent to narrow down which connectors to look up.
    Returns up to 6 most relevant connector names.
    """
    text_lower = user_text.lower()
    matches = set()

    # Check keyword aliases
    for keyword, connectors in KEYWORD_ALIASES.items():
        if keyword in text_lower:
            matches.update(connectors)

    # Also check against catalog connector names directly
    catalog = _load_catalog()
    for entry in catalog["index"]:
        name_lower = entry["name"].lower()
        if name_lower in text_lower or text_lower in name_lower:
            matches.add(entry["name"])

    return sorted(matches)[:6]


def list_connector_names() -> dict:
    """Return categorized connector names from the catalog."""
    catalog = _load_catalog()
    sources = []
    sinks = []
    for entry in catalog["index"]:
        if "source" in entry["types"]:
            sources.append(entry["name"])
        if "sink" in entry["types"]:
            sinks.append(entry["name"])
    transforms = list(TRANSFORMS.keys())
    return {"sources": sources, "sinks": sinks, "transforms": transforms}


def validate_connector_options(connector_name: str, provided_keys: set[str]) -> dict:
    """Validate that provided config keys satisfy the connector's requirements.

    Returns: {"valid": bool, "missing_required": [...], "unknown_keys": [...]}
    """
    catalog = _load_catalog()
    detail = catalog["connectors"].get(connector_name)
    if not detail:
        return {"valid": True, "missing_required": [], "unknown_keys": [], "note": "connector not in catalog"}

    required_keys = {opt["key"] for opt in detail.get("required", [])}
    optional_keys = {opt["key"] for opt in detail.get("optional", [])}
    all_known = required_keys | optional_keys

    # Build fallback map: primary_key -> set of fallback keys
    # A required key is satisfied if the primary key OR any fallback key is present
    fallback_map: dict[str, set[str]] = {}
    for opt in detail.get("required", []) + detail.get("optional", []):
        fb = opt.get("fallback_keys", [])
        if fb:
            fallback_map[opt["key"]] = set(fb)
            all_known.update(fb)

    missing = set()
    for key in required_keys:
        if key in provided_keys:
            continue
        fallbacks = fallback_map.get(key, set())
        if not (fallbacks & provided_keys):
            missing.add(key)

    unknown = provided_keys - all_known

    return {
        "valid": len(missing) == 0,
        "missing_required": sorted(missing),
        "unknown_keys": sorted(unknown),
    }
