apiVersion: flink.apache.org/v1alpha1
kind: FlinkDeployment
metadata:
  namespace: {{ .Values.metadata.namespace }}
  name: {{ .Values.metadata.name }}
spec:
  image: {{ .Values.spec.image }}
  flinkVersion: v1_14
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: {{ .Values.spec.flinkConf.numberOfTaskSlots | quote }}
  serviceAccount: flink
  jobManager:
    replicas: {{ .Values.spec.jobManager.replicas }}
    resource:
      memory: {{ .Values.spec.jobManager.resource.memory }}
      cpu: {{ .Values.spec.jobManager.resource.cpu }}
  taskManager:
    resource:
      memory: {{ .Values.spec.taskManager.resource.memory }}
      cpu: {{ .Values.spec.taskManager.resource.cpu }}
  podTemplate:
    spec:
      containers:
        - name: {{ .Values.spec.podTemplate.containers.name }}
          volumeMounts:
            - mountPath: {{ .Values.spec.podTemplate.containers.volumeMounts.mountPath }}
              name: {{ .Values.spec.podTemplate.containers.volumeMounts.name }}
      volumes:
        - name: {{ .Values.spec.podTemplate.volumes.name }}
          configMap:
            name: {{ .Values.spec.podTemplate.volumes.configMap }}
  job:
    jarURI: {{ .Values.spec.job.jarURI }}
    entryClass: org.apache.seatunnel.core.flink.SeatunnelFlink
    args: {{ .Values.spec.job.args }}
    parallelism: {{ .Values.spec.job.parallelism }}
    upgradeMode: {{ .Values.spec.job.upgradeMode }}

