# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: publish-e2e-spark-images

on:
  pull_request:
    paths:
      - '.github/workflows/publish-e2e-spark-images.yaml'
      - 'seatunnel-e2e/seatunnel-e2e-common/src/test/docker/spark/**'
  workflow_dispatch:

concurrency:
  group: publish-e2e-spark-images
  cancel-in-progress: false

jobs:
  build:
    if: github.event_name == 'pull_request' || github.repository != 'apache/seatunnel'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Spark E2E images
        working-directory: seatunnel-e2e/seatunnel-e2e-common/src/test/docker/spark
        run: docker buildx bake

  publish:
    if: github.event_name == 'workflow_dispatch' && github.repository == 'apache/seatunnel'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Spark E2E images
        working-directory: seatunnel-e2e/seatunnel-e2e-common/src/test/docker/spark
        run: docker buildx bake --push
